# Generated by Django 4.0.1 on 2022-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('class_type', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=20)),
                ('date', models.DateField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(default='common', max_length=30)),
                ('credit', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
