# Generated by Django 4.0.1 on 2022-01-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butfitapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butfitapp.class', verbose_name='class_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butfitapp.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
