# Generated by Django 4.0.1 on 2022-01-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butfitapp', '0003_alter_credit_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butfitapp.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butfitapp.user')),
            ],
            options={
                'db_table': 'bookinglogs',
            },
        ),
    ]
