# Generated by Django 4.0.1 on 2022-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butfitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
